# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(350, 430)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(350, 430))
        font = QtGui.QFont()
        font.setFamily("Actor")
        MainWindow.setFont(font)
        MainWindow.setToolTip("")
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.subtitle = QtWidgets.QLabel(self.centralwidget)
        self.subtitle.setGeometry(QtCore.QRect(30, 40, 279, 18))
        font = QtGui.QFont()
        font.setFamily("Rounded Mplus 1c Light")
        font.setPointSize(10)
        self.subtitle.setFont(font)
        self.subtitle.setObjectName("subtitle")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(100, 0, 134, 46))
        font = QtGui.QFont()
        font.setFamily("Rounded Mplus 1c Light")
        font.setPointSize(25)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.inputPathToTranscript = QtWidgets.QTextEdit(self.centralwidget)
        self.inputPathToTranscript.setEnabled(True)
        self.inputPathToTranscript.setGeometry(QtCore.QRect(31, 90, 207, 30))
        self.inputPathToTranscript.setStyleSheet("background-color: #FFFFFF;\n"
"border-color: rgba(0, 0, 0, 0.0578);\n"
"border-radius: 3px;\n"
"border-style: solid;\n"
" border-width: 1px;")
        self.inputPathToTranscript.setReadOnly(True)
        self.inputPathToTranscript.setObjectName("inputPathToTranscript")
        self.subtitle_2 = QtWidgets.QLabel(self.centralwidget)
        self.subtitle_2.setGeometry(QtCore.QRect(31, 70, 279, 18))
        font = QtGui.QFont()
        font.setFamily("Actor")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.subtitle_2.setFont(font)
        self.subtitle_2.setObjectName("subtitle_2")
        self.inputPathToTranslate = QtWidgets.QTextEdit(self.centralwidget)
        self.inputPathToTranslate.setEnabled(True)
        self.inputPathToTranslate.setGeometry(QtCore.QRect(30, 150, 207, 30))
        self.inputPathToTranslate.setStyleSheet("background-color: #FFFFFF;\n"
"border-color: rgba(0, 0, 0, 0.0578);\n"
"border-radius: 3px;\n"
"border-style: solid;\n"
" border-width: 1px;")
        self.inputPathToTranslate.setReadOnly(True)
        self.inputPathToTranslate.setObjectName("inputPathToTranslate")
        self.subtitle_3 = QtWidgets.QLabel(self.centralwidget)
        self.subtitle_3.setGeometry(QtCore.QRect(30, 130, 279, 18))
        font = QtGui.QFont()
        font.setFamily("Actor")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.subtitle_3.setFont(font)
        self.subtitle_3.setObjectName("subtitle_3")
        self.comboOrigin = QtWidgets.QComboBox(self.centralwidget)
        self.comboOrigin.setGeometry(QtCore.QRect(30, 213, 101, 22))
        self.comboOrigin.setStyleSheet("/* Light/Fill Color/Control/Default */\n"
"background: rgba(255, 255, 255, 0.7);\n"
"border-color: rgba(0, 0, 0, 0.0578);\n"
"border-radius: 3px;\n"
"width: 80px;\n"
"height: 22px;\n"
"color: rgba(0, 0, 0, 0.8956);\n"
"font-family: \'Actor\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 20px;\n"
"border-style: solid;\n"
" border-width: 1px;")
        self.comboOrigin.setObjectName("comboOrigin")
        self.comboOrigin.addItem("")
        self.comboOrigin.addItem("")
        self.comboOrigin.addItem("")
        self.subtitle_4 = QtWidgets.QLabel(self.centralwidget)
        self.subtitle_4.setGeometry(QtCore.QRect(30, 190, 101, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subtitle_4.sizePolicy().hasHeightForWidth())
        self.subtitle_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Actor")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.subtitle_4.setFont(font)
        self.subtitle_4.setAutoFillBackground(False)
        self.subtitle_4.setObjectName("subtitle_4")
        self.comboTranslate = QtWidgets.QComboBox(self.centralwidget)
        self.comboTranslate.setGeometry(QtCore.QRect(210, 213, 101, 22))
        self.comboTranslate.setStyleSheet("/* Light/Fill Color/Control/Default */\n"
"background: rgba(255, 255, 255, 0.7);\n"
"border-color: rgba(0, 0, 0, 0.0578);\n"
"border-radius: 3px;\n"
"width: 80px;\n"
"height: 22px;\n"
"color: rgba(0, 0, 0, 0.8956);\n"
"font-family: \'Actor\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 20px;\n"
"border-style: solid;\n"
" border-width: 1px;")
        self.comboTranslate.setObjectName("comboTranslate")
        self.comboTranslate.addItem("")
        self.comboTranslate.addItem("")
        self.comboTranslate.addItem("")
        self.subtitle_5 = QtWidgets.QLabel(self.centralwidget)
        self.subtitle_5.setGeometry(QtCore.QRect(210, 190, 101, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subtitle_5.sizePolicy().hasHeightForWidth())
        self.subtitle_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Actor")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.subtitle_5.setFont(font)
        self.subtitle_5.setAutoFillBackground(False)
        self.subtitle_5.setObjectName("subtitle_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 213, 21, 20))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/teste/teste.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.comboModel = QtWidgets.QComboBox(self.centralwidget)
        self.comboModel.setGeometry(QtCore.QRect(70, 290, 191, 22))
        self.comboModel.setStyleSheet("/* Light/Fill Color/Control/Default */\n"
"background: rgba(255, 255, 255, 0.7);\n"
"border-color: rgba(0, 0, 0, 0.0578);\n"
"border-radius: 3px;\n"
"width: 80px;\n"
"height: 22px;\n"
"color: rgba(0, 0, 0, 0.8956);\n"
"font-family: \'Actor\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 20px;\n"
"border-style: solid;\n"
" border-width: 1px;")
        self.comboModel.setObjectName("comboModel")
        self.comboModel.addItem("")
        self.comboModel.addItem("")
        self.comboModel.addItem("")
        self.subtitle_6 = QtWidgets.QLabel(self.centralwidget)
        self.subtitle_6.setGeometry(QtCore.QRect(80, 260, 191, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subtitle_6.sizePolicy().hasHeightForWidth())
        self.subtitle_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Actor")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.subtitle_6.setFont(font)
        self.subtitle_6.setAutoFillBackground(False)
        self.subtitle_6.setObjectName("subtitle_6")
        self.inputPathToTranscript.raise_()
        self.subtitle.raise_()
        self.title.raise_()
        self.subtitle_2.raise_()
        self.inputPathToTranslate.raise_()
        self.subtitle_3.raise_()
        self.comboOrigin.raise_()
        self.subtitle_4.raise_()
        self.comboTranslate.raise_()
        self.subtitle_5.raise_()
        self.label.raise_()
        self.comboModel.raise_()
        self.subtitle_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.subtitle.setText(_translate("MainWindow", "Traduza legendas usando Inteligência Artificial"))
        self.title.setText(_translate("MainWindow", "TraduzAI"))
        self.inputPathToTranscript.setPlaceholderText(_translate("MainWindow", "C:/Videos/Legendas/english.srt"))
        self.subtitle_2.setText(_translate("MainWindow", "O que deseja traduzir?"))
        self.inputPathToTranslate.setPlaceholderText(_translate("MainWindow", "C:/Videos/Legendas/traducao.srt"))
        self.subtitle_3.setText(_translate("MainWindow", "Onde deseja salvar?"))
        self.comboOrigin.setCurrentText(_translate("MainWindow", "English"))
        self.comboOrigin.setItemText(0, _translate("MainWindow", "English"))
        self.comboOrigin.setItemText(1, _translate("MainWindow", "Portuguese"))
        self.comboOrigin.setItemText(2, _translate("MainWindow", "Spanish"))
        self.subtitle_4.setText(_translate("MainWindow", "Origem:"))
        self.comboTranslate.setCurrentText(_translate("MainWindow", "Portuguese"))
        self.comboTranslate.setItemText(0, _translate("MainWindow", "Portuguese"))
        self.comboTranslate.setItemText(1, _translate("MainWindow", "English"))
        self.comboTranslate.setItemText(2, _translate("MainWindow", "Spanish"))
        self.subtitle_5.setText(_translate("MainWindow", "Tradução:"))
        self.comboModel.setCurrentText(_translate("MainWindow", "facebook/m2m100_1.2B"))
        self.comboModel.setItemText(0, _translate("MainWindow", "facebook/m2m100_1.2B"))
        self.comboModel.setItemText(1, _translate("MainWindow", "facebook/wmt19-en-de"))
        self.comboModel.setItemText(2, _translate("MainWindow", "facebook/wmt19-de-en"))
        self.subtitle_6.setText(_translate("MainWindow", "Modelo de IA para tradução:"))
